== About

image::https://img.shields.io/badge/Java%20Development%20Kit-7%2B-blue.svg[JDK]
image::https://img.shields.io/badge/Spring%20Boot-1.1.3-green.svg[Spring Boot]
image::https://img.shields.io/badge/Maven-3.0%2B-blue.svg[Maven]

Article 59 of the new Public Procurement Directive 2014/24/EC mandates the use of the European Single Procurement
Document ({homepage}). The {homepage} should be made available as an electronic form. In order to reap the full benefits of the
{homepage}, the Commission should provide this in the form of a service that can be used by the contracting authorities (CAs)
and economic operators (EOs).

The main objective of the {homepage} is to reduce the administrative burden and lead to considerable simplification of
participation in public procurement procedures for buyers and suppliers. The service will reduce that burden by removing
the need to produce a substantial number of certificates and documentation related to exclusion and selection criteria.
This will answer to obstacles reported by many suppliers and especially SMEs.

The {homepage} service is provided as a web based system and the output of it provided as XML files. In addition,
the {homepage} service will become part of the Connecting European Facility (CEF) eProcurement DSI (Digital Service
Infrastructure). The CEF will help that the Member States will implement an {homepage} service in their country and
provide additional services to their users.

Will be a Web Based Service provided by the Commission to the Member States and European Institutions. It provides a
web-based service to exchange a structured e-procurement information  in an harmonised way. The system is not a
persistent storage but rather a transformation service which enables to manage xml-based documents for each
procurement submitted.