== About

image::https://img.shields.io/badge/Java%20Development%20Kit-7%2B-blue.svg?style=flat[JDK]
image::https://img.shields.io/badge/Spring%20Boot-1.3.2-green.svg?style=flat[Spring Boot]
image::https://img.shields.io/badge/Maven-3.0%2B-blue.svg?style=flat[Maven]

Article 59 of the new Public Procurement Directive 2014/24/EC mandates the use of the European Single Procurement
Document ({homepage}). The {homepage} should be made available as an electronic form. In order to reap the full benefits of the
{homepage}, the Commission should provide this in the form of a service that can be used by the contracting authorities (CAs)
and economic operators (EOs).

The main objective of the {homepage} is to reduce the administrative burden and lead to considerable simplification of
participation in public procurement procedures for buyers and suppliers. The service will reduce that burden by removing
the need to produce a substantial number of certificates and documentation related to exclusion and selection criteria.
This will address the obstacles reported by many suppliers and especially SMEs.

The ESPD service is a web-based solution which allows the Member States and European Institutions to exchange structured
e-procurement information in a harmonised manner. The system is not a persistent storage but rather a transformation
service which enables the management of XML based documents for each procurement submitted.

The {homepage} service is provided as a web-based system and the output of it provided as XML files. In addition,
the {homepage} service will become part of the Connecting European Facility (CEF) eProcurement DSI (Digital Service
Infrastructure). The CEF will help the Member States to implement an {homepage} service in their own country and
provide additional services to their users.

