:sourcedir: ../java/eu/europa/ec/grow/espd
:homepage: https://ec.europa.eu/espd[ESPD]
:espd: https://ec.europa.eu/espd[ESPD]
:appVersion: 2017.03.02
:maven: https://maven.apache.org[Maven]
:tomcat: https://tomcat.apache.org[Tomcat]
:springBoot: http://projects.spring.io/spring-boot/[Spring Boot]
:spring: https://projects.spring.io/spring-framework/[Spring]
:springMvc: http://docs.spring.io/autorepo/docs/spring/3.2.x/spring-framework-reference/html/mvc.html[Spring MVC]
:logback: http://logback.qos.ch/[Logback]
:slf4j: http://www.slf4j.org/[SLF4J]
:lombok: https://projectlombok.org/[Lombok]
:wro4j: https://github.com/wro4j/wro4j[WRO4J]
:intellij: https://www.jetbrains.com/idea[IntelliJ]
:eclipse: https://eclipse.org/downloads[Eclipse]
:javaMelody: https://github.com/javamelody/javamelody/wiki[Java Melody]
:jaxb: https://jaxb.java.net[JAXB]
:jodaTime: http://www.joda.org/joda-time/[Joda-Time]
:spock: http://spockframework.github.io/spock/docs/1.0/index.html[Spock Framework]
:groovy: http://www.groovy-lang.org/[Groovy]
:espdGitRepo: https://github.com/ESPD/espd.git[ESPD Git repository]
:tiles: https://tiles.apache.org/[Apache Tiles]
:bootstrap: http://getbootstrap.com/[Twitter Bootstrap]
:piwik: http://piwik.org/[Piwik]
:jquery: https://jquery.com/[jQuery]
:rest: https://en.wikipedia.org/wiki/Representational_state_transfer[REST]
:ted: http://ted.europa.eu[TED]

== Installation

=== Configure the Git repository

. Fork the {espdGitRepo} by clicking on the `Fork` button on the top-right corner of the repository page. Forking a
repository allows you to freely experiment with changes without affecting the original project. Most commonly, forks
are used to either propose changes to someone else's project or to use someone else's project as a starting point for
your own idea.
. Create a local clone of your fork
.. On GitHub, navigate to your fork of the {espdGitRepo}.
.. Under your repository name, click the `Copy to clipboard` button to copy the URL for the repository.
.. Run the `git clone &#60;URL&#62;` command on your computer, after pasting the URL you copied in the previous step. Now, you have a local copy of
your fork of the {espdGitRepo}.
. Configure Git to sync your fork with the original {espdGitRepo}. When you fork a project in order to propose
changes to the original repository, you can configure Git to pull changes from the original, or _upstream_, repository
into the local clone of your fork.
.. On GitHub, navigate to the {espdGitRepo} repository.
.. Under the repository name, click the `Copy to clipboard` button to copy the URL for the repository.
.. Change directories to the location of the fork you cloned in the previous step.
.. Execute `git remote -v` to see the current configured remote repositories for your fork.
.. Type `git remote add upstream &#60;URL&#62;` by pasting the URL you copied in Step b.
.. To verify the new upstream repository you've specified for your fork, execute `git remote -v` again. You should see
the URL for your fork as `origin`, and the URL for the original repository as `upstream`.

[source,bash]
----
$ git remote -v
origin    https://github.com/YOUR_USERNAME/YOUR_FORK.git (fetch)
origin    https://github.com/YOUR_USERNAME/YOUR_FORK.git (push)
upstream  https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git (fetch)
upstream  https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git (push)
----

Now you can keep your fork synced with the `upstream` repository with a few Git commands. For more information,
please see the https://help.github.com/articles/syncing-a-fork/[Syncing a fork] page.

[NOTE]
Quite often people working in a team and using the same repository or upstream prefer different operating systems.
This may result in problems with line endings because Unix, Linux, and OS X use LF and Windows uses CRLF to denote
the end of a line. To have Git solve such problems automatically, you need to set the `core.autocrlf` attribute to
`true` on Windows and to `input` on Linux and OS X. For more details on the meaning of the `core.autocrlf` attribute,
see the article https://help.github.com/articles/dealing-with-line-endings[Dealing with Line Endings]. You can change the configuration manually by running
`git config --global core.autocrlf true` on Windows or `git config --global core.autocrlf input` on Linux and OS X.

[NOTE]
Each major application version will have a dedicated branch so you can checkout the code for a particular version. The name convention adopted for release branches is YYYY.MM.
The master branch contains the version currently deployed in production.
The develop branch contains the code for the next version of ESPD.
The gh-pages branch is reserved for documentation.
If you want to be isolated from changes you should branch from master or from a specific release branch.

=== Building and running the ESPD application

This section goes into detail about how you can build and run the {homepage} application.

==== Building the application

The {homepage} uses {maven} as the primary build system and is structured as a multi-module Maven project.

After getting access to the source code and cloning it on your computer, you can now build the project with {maven}.

. Change directories to the location of the cloned Git repository on your machine.
. Perform a `mvn clean package` and the project dependencies should be downloaded and the `espd-web` and `espd-docs` modules should be built.

==== Running the application

The easiest way to run the application is with an embedded container (default is Tomcat) by invoking the `main` method
from the `eu.europa.ec.grow.espd.config.EspdApplication` class in the same way as you would start a normal Java application.

. Perform a `mvn clean package` from the root folder of the project:
.. The build should generate a WAR file at `${baseDir}/espd-web/target/espd-web.war`
. Add the following startup parameters to you server:
.. `-Dspring.profiles.active=${your desired profile}` specifies the http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#boot-features-external-config-profile-specific-properties[Spring Boot profile] to be used
.. `-Dted.api.user=${your TED user}` where `${your TED user}` is replaced by the TED API username
.. `-Dted.api.password=${your TED password}` where `${your TED password}` must be replaced by the TED API password

The application can be started with a shell script that can contain the following minimum configuration:

[source,bash]
.start.sh
----
java -Dspring.profiles.active=prod -Xms768m -Xmx768m -jar espd-web.war
----

Other application parameters can also be specified in exactly the same way, i.e. by prefixing them with a `-D` followed
by the name of the parameter. You can consult the `application.properties` files for finding out the available options
but please note that the ones specified at start-up have higher precedence than the ones specified in the `.properties`
files.

[NOTE]
It is recommended to set up the context path of the application when running in the embedded mode. This can be done in the application.properties file located in the espd-web project resources folder.
[source,properties]
.application.properties
----
# Context path of the application
server.context-path=/espd
----

==== Deploying the web application on a servlet container

The application can be deployed as a WAR file on a Servlet 3 compliant container such as Tomcat. For this, you need to package it as a WAR for the
`non-embedded` Maven profile and provide some startup parameters on your server.

. Perform a `mvn clean package -Pnon-embedded` from the root folder of the project:
.. The build should generate a WAR file at `${baseDir}/espd-web/target/espd-web.war`
. The other steps are similar to the embedded server deployment mode

==== Using an IDE

You can also run the {homepage} application from your favourite IDE by importing the project as a multi-module Maven project first.
[NOTE]
You will need to install the {lombok} plugin for your particular IDE. Lombok is a library designed to reduce Java boilerplate code through the use of annotations.
[NOTE]
If you have problems importing the project in {eclipse} try running the {maven} command `mvn eclipse:eclipse` before the import.
If after the import the Problems view display errors of type `Plugin execution not covered by lifecycle configutation` right-click on the error and set Eclipse to ignore the execution of the plugin.
